services:
  user_db:
    image: postgres
    container_name: postgres_user_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
  cache:
    image: redis
    restart: always
    ports:
      - "${CACHE_PORT}:6379"
