spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  liquibase:
    change-log: classpath:/db/changelog/migrations.xml
  data:
    redis:
      host: ${CACHE_HOST}
      port: ${CACHE_PORT}
  cache:
    type: redis
logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG